find_bits.exe: find_bits.o find_bits_functions.o
	gcc -Wall -ansi -pedantic -o find_bits find_bits.o find_bits_functions.o
find_bits.o: find_bits.c
	gcc -Wall -ansi -pedantic -c find_bits.c -o find_bits.o
find_bits_functions.o: find_bits_functions.c
	gcc -Wall -ansi -pedantic -c find_bits_functions.c -o find_bits_functions.o
	
	

